-- OllaBridge Server Schema
-- Import this into your shared hosting MySQL database once.
-- Then upload the PHP files into a folder called /ollabridge/ on your server.

CREATE TABLE IF NOT EXISTS `ollabridge_jobs` (
    `id`         VARCHAR(36)  NOT NULL                COMMENT 'UUID — generated by submit_job.php',
    `type`       ENUM('generate','chat') NOT NULL DEFAULT 'generate',
    `model`      VARCHAR(100) NOT NULL DEFAULT 'qwen2.5-coder',
    `payload`    LONGTEXT     NOT NULL                COMMENT 'JSON: {prompt} for generate, {messages:[]} for chat',
    `images`     TEXT         DEFAULT NULL            COMMENT 'JSON array of public image URLs (optional)',
    `status`     ENUM('pending','processing','completed','failed') NOT NULL DEFAULT 'pending',
    `result`     LONGTEXT     DEFAULT NULL            COMMENT 'AI response text, written by the Python worker',
    `error_msg`  TEXT         DEFAULT NULL            COMMENT 'Error details if status=failed',
    `created_at` TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (`id`),
    KEY `idx_status`  (`status`),
    KEY `idx_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
